#!/bin/zsh -f

# global aliases
alias -g SAD='&> /dev/null &|'
alias -g ...='../..'
alias -g ....='../../..'
alias -g .....='../../../..'

# file associations
alias -s html=uzbl --uri=
alias -s org=uzbl --uri=
alias -s com=uzbl --uri=
alias -s html=uzbl --uri=
alias -s org=uzbl --uri=
alias -s sh=bash
alias -s zsh=zsh
alias -s gif=feh
alias -s png=feh
alias -s jpg=feh
alias -s pdf=evince
alias -s rb=ruby
alias -s pl=perl
alias -s exe=wine

# better programs
alias_exists top htop
alias_exists more most
alias_exists ping mtr
alias_exists mpc boogie

# ls shortcuts
alias l="ls"
alias lsa="l -ld .*"
alias lsbig="l -lSh *(.) | head"
alias lsd="l -ld *(-/DN)"
alias lsnew="l -lrt *(.) | tail"
alias lsold="l -lrt *(.) | head"
alias lssmall="l -lSh *(.) | head"
alias lsnoext="l | grep -v '\.'"
alias lsd='ls -ld *(-/DN)'
alias l.='ls -d .[^.]*'
alias ll="l -l"
alias la="l -a"
alias lla="l -la"
alias lg="l | grep -i $1"


# nocorrect
alias rm='nocorrect rm'
alias cp='nocorrect cp'
alias mv='nocorrect mv'
alias ln='nocorrect ln'
alias mkdir='nocorrect mkdir -p'

# shortcuts
alias which="whence -a"
alias c="clear"
alias s='sudo -E'
alias su='s -s'
alias ej='eject -T'
alias k='killall'
alias e='vim'
alias t='thunar'
alias m="nice -n1 mplayer"
alias ml="nice -n1 mplayer -loop 0"
alias mls="nice -n1 mplayer -loop 0 -shuffle"
alias mn="nice -n1 mplayer -nosound"
alias find='LC_ALL="C" find'
alias grep='LC_ALL="C" grep'
alias g="grep"
alias p="${PAGER}"
alias repo="cd /var/db/paludis/repositories/"
alias a='ack'

# default options
alias ssh='ssh -AX'
alias ps='ps auxwww'
alias cpan="perl -MCPAN -e shell"
alias wget="wget -c"
alias ncmpc="ncmpc -c"
alias vim="vim -p"
alias tmux="tmux -2"
alias dispatch-conf="s dispatch-conf"
alias most="most +s +u"
alias ri="ri -Tf ansi"
alias poweroff="s poweroff"
alias reboot="s reboot"
alias shred='nocorrect ionice -c3 /usr/bin/shred -fuzv'
alias wipe='nocorrect ionice -c3 /usr/bin/wipe -l1 -v -r'
alias pwgen='pwgen -sBync 12'
alias grep="grep -Hn"
alias tudu='LC_ALL="C" tudu'

# Rails
alias tlog='tail -f log/development.log'
alias rst='touch tmp/restart.txt'
alias migrate='rake db:migrate db:test:clone'
alias remigrate="rm db/*.sqlite3; rake db:migrate:redo && rake db:schema:dump && rake db:test:prepare"
alias prod='export RAILS_ENV="production"'
alias dev='export RAILS_ENV="dev"'
alias b='bundle'

# git
alias gl="git pull"
alias gc="git clone"
alias gp='git push'
alias gpp='git push origin master:refs/heads/master'
alias gd='git diff'
alias gca='git commit -a'
alias gco='git checkout'
alias gb='git branch'
alias gba='git branch -a'
alias gs='git status'
alias ga='git add'
alias gd='git diff'
alias gci='git commit -v'
alias grm='git rm $(git ls-files --deleted)'
alias gaa='git ls-files -o --exclude-per-directory=.gitignore | xargs git add'
alias glg='git log --graph --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr)%Creset" --abbrev-commit --date=relative'
alias rlog='git log --pretty=format:"%h %Cblue%cr%Creset %cn %Cgreen%s%Creset"'
alias glo='git log --date=local --pretty=full --stat'
alias mkpatch="git format-patch --stdout -M -C -C -1"
alias gdp="git push origin && git push github"

# new commands
alias xlog="sudo grep --binary-files=without-match --color -nsie '(EE)' -e '(WW)' /var/log/Xorg.0.log"
alias sd='export DISPLAY=:0.0'
alias cup='cvs -z3 update -Pd'
alias fixdbus="dbus-uuidgen --ensure"
alias wp="~/bin/wallpaper"
alias biosinfo='sudo dmidecode'
alias gnp="git-notpushed"
alias wcyy="mplayer http://68.142.81.164:80/citadelcc_WCYY_FM\?MSWMExt\=.asf"
alias wkit="mplayer http://64.92.199.73/WKIT-FM"
alias gis="git status | grep --color=always '^[^a-z]\+\(new file:\|modified:\)' | cut -d'#' -f2-"
alias dosbox="dosbox -conf ~/.dosbox.conf"
alias lk='lynx -dump http://kernel.org/kdist/finger_banner'
alias ra="echo 'awful.util.restart()' | awesome-client -"
alias sv="gvim --remote-tab-silent"
alias smv="s mv"
alias srm="s rm"
alias tmr="tmux attach-session"
alias images='feh -d -x -F -Z $PWD'
alias wgetlist="wget -c -i"
alias become="sudo -s -H -u $1"
alias runas="sudo -H -u $1 $@"
alias fixkey='ssh-keygen -i -f'
alias hammertime='ruby -rhammertime'
alias sendpatch="git format-patch --stdout -M -C -C -1 | wgetpaste -r"
alias gemu="gem update --system && gem update"
alias gemi="gem install --no-ri --include-dependencies"
alias gems="gem search -b"
alias gemr="gem uninstall"
alias gemc="gem clean"
alias geminstaller="geminstaller -s -c ${HOME}/.geminstaller.yaml"
alias minicom='minicom -c on'
alias mkchangelog='git log --stat --name-only --date=short --abbrev-commit > ChangeLog'
alias googlecl='/usr/bin/google'
alias playaudio='mplayer -cdrom-device /dev/cdrom cdda://'
alias ad='asciidoc -n -a data-uri -a toc'
alias wget-mirror="wget -e robots=off --timestamping --recursive --level=inf --no-parent --page-requisites --convert-links --backup-converted"
alias wget-fullpage="wget -e robots=off --page-requisites --span-hosts --convert-links"

#games
alias torchlight="wine ~/.wine/drive_c/Program\ Files/Runic\ Games/Torchlight/Torchlight.exe"
alias savage="~/code/bin/savage/savage.sh"

# vim: set et sw=4 sts=4 ts=4 ft=zsh :
