#!/bin/zsh -f

# file associations
alias -s html=uzbl --uri=
alias -s org=uzbl --uri=
alias -s com=uzbl --uri=
alias -s html=uzbl --uri=
alias -s org=uzbl --uri=
alias -s sh=bash
alias -s zsh=zsh
alias -s gif=feh
alias -s png=feh
alias -s jpg=feh
alias -s pdf=evince
alias -s rb=ruby
alias -s pl=perl

# better programs
alias_exists top htop
alias_exists more most
alias_exists ping mtr

# ls shortcuts
alias lsa='ls -ld .*' 
alias lsbig='ls -lSh *(.) | head' 
alias lsd='ls -ld *(-/DN)' 
alias lsnew='ls -lrt *(.) | tail' 
alias lsold='ls -lrt *(.) | head' 
alias lssmall='ls -lSh *(.) | head' 
alias lsnoext="ls | grep -v '\.'"
alias ll="ls -l"
alias l.='ls -d .[^.]*'
alias lsd='ls -ld *(-/DN)'
alias la="ls -a"
alias l="ls"
alias lg='ls | grep -i $1'

# nocorrect 
alias rm='nocorrect rm'
alias cp='nocorrect cp'
alias mv='nocorrect mv'
alias ln='nocorrect ln'
alias mkdir='nocorrect mkdir -p'

# shortcuts
alias which="whence"
alias p='ping'
alias h='history'
alias c="clear"
alias s='sudo -E'
alias su='s -s'
alias ej='eject'
alias k='killall'
alias e='gvim'
alias v='vim'
alias t='thunar'
alias m="nice -n1 mplayer"
alias ml="nice -n1 mplayer -loop 0"
alias mls="nice -n1 mplayer -loop 0 -shuffle"
alias mn="nice -n1 mplayer -nosound"
alias g='grep'

# default options
alias ssh='ssh -qAX'
alias ps='ps auxwww'
alias cpan="perl -MCPAN -e shell"
alias wget="wget -c"
alias ncmpc="ncmpc -c"
alias vim="vim -p"
alias tmux="tmux -2"
alias most="most +s +u"
alias ri="ri -Tf ansi"
alias poweroff='s poweroff'
alias reboot='s reboot'
alias ketchup='ketchup -G -a /usr/portage/distfiles'
alias shred='nocorrect ionice -c3 /usr/bin/shred -fuzv'
alias wipe='nocorrect ionice -c3 /usr/bin/wipe -l1 -v -r'
alias grep='grep -Hn --color=always'
alias pwgen='pwgen -sBnc 10'

# Rails
alias sc='script/console'
alias sp='script/plugin'
alias db='script/dbconsole'
alias a='autotest -rails'
alias tlog='tail -f log/development.log'
alias rst='touch tmp/restart.txt'

# new commands
alias xlog="sudo grep --binary-files=without-match --color -nsie '(EE)' -e '(WW)' /var/log/Xorg.0.log"
alias sd='export DISPLAY=:0.0'
alias cup='cvs -z3 update -Pd'
alias fixdbus="dbus-uuidgen --ensure"
alias wp="~/code/bin/wallpaper/wallpaper.rb"
alias gi='sudo gem install --no-ri --include-dependencies'
alias gs='gem search -b'
alias burniso='wodim -v dev=/dev/cdrw'
alias burndvdiso='growisofs -speed=8 -dvd-compat -Z /dev/dvdrw=$1'
alias biosinfo='sudo dmidecode'
alias gnp="git-notpushed"
alias savage="~/code/bin/savage/savage.sh"
alias wcyy="mplayer http://68.142.81.164:80/citadelcc_WCYY_FM\?MSWMExt\=.asf"
alias wkit="mplayer http://64.92.199.73/WKIT-FM"
alias gis="git status | grep --color=always '^[^a-z]\+\(new file:\|modified:\)' | cut -d'#' -f2-"
alias lk='lynx -dump http://kernel.org/kdist/finger_banner'
alias g='grep -Hn --color=always'
alias ra="echo 'awful.util.restart()' | awesome-client -"
alias sv="gvim --remote-tab-silent"
alias lvim="vim -c \"normal '0\""
alias geminstaller='sudo geminstaller -s -c $HOME/.geminstaller.yaml'
alias gem_remove_all="gem uninstall -x --a --ignore-dependencies `gem list -q -l --no-details --no-versions `"
alias smv="s mv"
alias srm="s rm"
alias installed='qlist -I | most'
alias n="nitrogen ~/media/images/wallpaper/"
alias grm='git rm $(git ls-files --deleted)'
alias encrypt="gpg -e -r Greg"
alias decrypt="gpg -d -r Greg"
alias tmr="tmux attach-session"
alias images='feh -d -x -F -Z $PWD'
alias wgetlist="wget -c -i"
alias become="sudo -s -H -u $1"
alias runas="sudo -H -u $1 $@"

# vim: set et sw=4 sts=4 ts=4 ft=zsh :
